mainPage:
     path: /
     controller: App\Controller\MainPage::mainPage
     methods: GET

searchPage:
     path: /search
     controller: App\Controller\SearchController::index
     methods: GET

tagsCloud:
     path: /tags-cloud
     controller: App\Controller\TagsCloudController::index
     methods: GET